[package]
name = "htl3r-itp"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
    "Tamara Marl <https://github.com/1047-25-HTL3R>",
]
license = "0BSD AND CC-BY-SA-4.0"
description = "HTL-Rennweg itp project document template."
repository = "https://github.com/1047-25-HTL3R/itp_project_typst_template"
keywords = ["ITP-Projekt", "ITP", "HTL Rennweg", "htl3r", "wien"]
categories = ["project"]
compiler = "0.13.0"
exclude = [
    ".git",
    ".github",
    "docs",
    "scripts",
    "tests",
    ".typstignore",
    "Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

[tool.typst-test]
vcs = "git"
